version: '2'
services:
  apim_rdbms:
    build:
        context: ../
        dockerfile: pattern-1/database/Dockerfile
    environment:
        MYSQL_ROOT_PASSWORD: root
  svnrepo:
    image: dockerhub.private.wso2.com/svnrepo
  gateway-manager:
    build:
      context: ../
      dockerfile: pattern-1/gateway-manager/Dockerfile
    environment:
      - SLEEP=60
    links:
      - nginx:apim-gateway-worker
      - nginx:apim-store
      - nginx:apim-publisher
      - nginx:apim-keymanager
      - nginx:mgt.gw.apim.wso2.org
  gateway-worker:
    build:
      context: ../
      dockerfile: pattern-1/gateway-worker/Dockerfile
    environment:
      - SLEEP=120
    links:
      - nginx:mgt.gw.apim.wso2.org
      - nginx:apim-store
      - nginx:apim-publisher
      - nginx:apim-keymanager
  store:
    build:
      context: ../
      dockerfile: pattern-1/store/Dockerfile
    environment:
      - SLEEP=180
    links:
      - nginx:mgt.gw.apim.wso2.org
      - nginx:apim-gateway-worker
      - nginx:apim-publisher
      - nginx:apim-keymanager
  publisher:
    build:
      context: ../
      dockerfile: pattern-1/publisher/Dockerfile
    environment:
      - SLEEP=200
    links:
      - nginx:mgt.gw.apim.wso2.org
      - nginx:apim-gateway-worker
      - nginx:apim-store
      - nginx:apim-keymanager
  keymanager:
    build:
      context: ../
      dockerfile: pattern-1/keymanager/Dockerfile
    environment:
      - SLEEP=5
    links:
      - nginx:mgt.gw.apim.wso2.org
      - nginx:apim-keymanager
      - nginx:apim-gateway-worker
      - nginx:apim-store
  nginx:
    build:
      context: ../
      dockerfile: pattern-1/nginx/Dockerfile
    environment:
      - SLEEP=60
    ports:
      - "443:9443"
      - "80:9763"
      - "8280:8280"
      - "8243:8243"

