version: '2'
services:
  apim_rdbms:
    build:
        context: ../
        dockerfile: pattern-3/database/Dockerfile
    environment:
        MYSQL_ROOT_PASSWORD: root
  svnrepo:
    image: dockerhub.private.wso2.com/svnrepo
  gateway-manager:
    build:
      context: ../
      dockerfile: pattern-3/gateway-manager/Dockerfile
    environment:
      - SLEEP=100
    links:
      - nginx:apim-gateway-worker
      - nginx:apim-store-km
      - nginx:apim-publisher
      - nginx:mgt.gw.apim.wso2.org
  gateway-worker:
    build:
      context: ../
      dockerfile: pattern-3/gateway-worker/Dockerfile
    environment:
      - SLEEP=160
    links:
      - nginx:mgt.gw.apim.wso2.org
      - nginx:apim-store-km
      - nginx:apim-publisher
  store-km:
    build:
      context: ../
      dockerfile: pattern-3/store-km/Dockerfile
    environment:
      - SLEEP=5
    links:
      - nginx:mgt.gw.apim.wso2.org
      - nginx:apim-gateway-worker
      - nginx:apim-publisher
      - nginx:apim-store-km
  publisher:
    build:
      context: ../
      dockerfile: pattern-3/publisher/Dockerfile
    environment:
      - SLEEP=100
    links:
      - nginx:mgt.gw.apim.wso2.org
      - nginx:apim-gateway-worker
      - nginx:apim-store-km
  nginx:
    build:
      context: ../
      dockerfile: pattern-3/nginx/Dockerfile
    environment:
      - SLEEP=60
    ports:
      - "443:9443"
      - "80:9763"
      - "8280:8280"
      - "8243:8243"

