version: '2'
services:
  dbms:
    container_name: apim_rdbms
    build:
        context: ../
        dockerfile: pattern-9/database/Dockerfile
    environment:
        MYSQL_ROOT_PASSWORD: root
  api-manager:
    container_name: api-manager
    build:
      context: ../
      dockerfile: pattern-9/api-manager/Dockerfile
    environment:
      - SLEEP=100
    links:
      - nginx:api-manager
  nginx:
    container_name: nginx
    build:
      context: ../
      dockerfile: pattern-9/nginx/Dockerfile
    environment:
      - SLEEP=100
    ports:
      - "443:9443"
      - "80:9763"
      - "8280:8280"
      - "8243:8243"

